In [1]:
import torch

In [5]:
# data_list = [1,2,3]
data_list = [[1,2,3], [4,5,6]]

tensor = torch.tensor(data_list)

print(tensor)
type(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Tensor

In [6]:
print(f'data type: {tensor.dtype}') # 텐서의 데이터 타입
print(f'number of dimensions: {tensor.ndim}')
print(f'shape: {tensor.shape}') # 텐서의 차원
print(f'device: {tensor.device}') # 텐서가 할당된 장치(cpu/gpu)
print(f'requires_grad" {tensor.requires_grad}') # 자동 미분을 기록할 지 여부

data type: torch.int64
number of dimensions: 2
shape: torch.Size([2, 3])
device: cpu
requires_grad" False


In [7]:
print(f'size: {tensor.size()}')

size: torch.Size([2, 3])


In [8]:
import numpy as np

data_np = np.array([
    [1,2,3],
    [4,5,6]
])

print(data_np)

tensor_np = torch.tensor(data_np)
print(tensor_np)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
tensor_from_numpy = torch.from_numpy(data_np)
print(tensor_from_numpy)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
numpy_as_tensor = torch.as_tensor(data_np)
print(numpy_as_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
data_np[0, 0] = -1

print(f'tensor.tensor:\n{tensor_np}')
print(f'tensor_from_numpy:\n{tensor_from_numpy}')
print(f'numpy_as_tensor:\n{numpy_as_tensor}')

tensor.tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor_from_numpy:
tensor([[-1,  2,  3],
        [ 4,  5,  6]])
numpy_as_tensor:
tensor([[-1,  2,  3],
        [ 4,  5,  6]])


In [15]:
print(tensor.dtype)
print(tensor_np.dtype)

torch.int64
torch.int64


In [16]:
tensor = torch.tensor([1., 1.5])
print(tensor.dtype)

torch.float32


In [20]:
tensor = torch.tensor([1,3,4], dtype=torch.float)
print(tensor.dtype)

torch.float32


In [22]:
tensor = torch.tensor([1.2, 3.4, 5.6], dtype=torch.float32)
int_tensor = tensor.to(torch.int32)
print(int_tensor)
print(int_tensor.dtype)

tensor([1, 3, 5], dtype=torch.int32)
torch.int32


In [23]:
# gpu_int_tensor = tensor.to(dtype=torch.int32, device='cuda')
# print(gpu_int_tensor)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [25]:
print(torch.rand(2, 3))
print(torch.rand([2, 3]))

print(torch.rand((2, 3)))

tensor([[0.0419, 0.5028, 0.3464],
        [0.3602, 0.4830, 0.2451]])
tensor([[0.9348, 0.5609, 0.3371],
        [0.2213, 0.3789, 0.1187]])
tensor([[0.5855, 0.0722, 0.8451],
        [0.1018, 0.2461, 0.0148]])


In [26]:
mu, sigma = 1, 10
mu + sigma * torch.rand(2, 3)

tensor([[5.8244, 9.1497, 6.0009],
        [8.9260, 4.9548, 6.0738]])

In [27]:
print(torch.zeros(2, 3))
print(torch.ones(2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [29]:
one_simple = torch.ones(2, 3) * 5
ful_simple = torch.full((2, 3), 7)

print(one_simple)
print(ful_simple)


tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[7, 7, 7],
        [7, 7, 7]])


파이썬 리스트 data_list와 NumPy array data_np가 주어져 있습니다. 이 두 데이터를 PyTorch 텐서로 만들어 주세요.
GURU

data_list에서 만든 텐서는 tensor_from_list 변수에 저장하고, data_np에서 만든 텐서는 tensor_from_np_array에 저장해야 합니다.

In [30]:
import numpy as np
import torch

data_list = [
    [1, 1],
    [-1, -1],
]
data_np = np.array(
    [
        [3, 4],
        [5, 6]
    ]
)

tensor_from_list = torch.tensor(data_list)
tensor_from_np_array = torch.tensor(data_np)

print(tensor_from_list)
print(tensor_from_np_array)

tensor([[ 1,  1],
        [-1, -1]])
tensor([[3, 4],
        [5, 6]])


In [33]:
tensor = torch.ones(2, 2)

np_arr = tensor.numpy()

In [34]:
np_arr2 = np.array(tensor)

In [35]:
tensor[0, 0] = -1

print(f'numpy() result\n{np_arr}')
print(f'np.array() result\n{np_arr2}')


numpy() result
[[-1.  1.]
 [ 1.  1.]]
np.array() result
[[1. 1.]
 [1. 1.]]


numpy() 메서드: 텐서와 Numpy 배열이 메모리를 공유함.

np.array(): 텐서의 데이터를 복사하여 새로운 Numpy 배열 생성

In [38]:
a = torch.tensor([
    [1,2,],
    [3,4]
])

b = torch.tensor([
    [1,1,],
    [2,2]
])

In [45]:
import time
start = time.time()

print(a + b)

print("time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간

tensor([[2, 3],
        [5, 6]])
time : 0.002429962158203125


In [46]:

start = time.time()

print(torch.add(a, b))

print("time :", time.time() - start)

tensor([[2, 3],
        [5, 6]])
time : 0.002577543258666992


In [47]:
torch.multiply(a, b)

tensor([[1, 2],
        [6, 8]])

In [48]:
torch.matmul(a, b)

tensor([[ 5,  5],
        [11, 11]])

In [51]:
a = torch.tensor(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8]
    ]
)

b = torch.tensor(
    [
        [1, 0, 0],
        [0, 0, 1]
    ]
)

print(f'a의 열 개수: {a.shape[1]}')
print(f'b의 행 개수: {b.shape[0]}')

a의 열 개수: 2
b의 행 개수: 2


In [52]:
torch.matmul(a,b)

tensor([[1, 0, 2],
        [3, 0, 4],
        [5, 0, 6],
        [7, 0, 8]])

In [53]:
a @ b

tensor([[1, 0, 2],
        [3, 0, 4],
        [5, 0, 6],
        [7, 0, 8]])

In [54]:
tensor_int = torch.tensor([1,2], dtype=torch.int32)
tensor_float = torch.tensor([3,4], dtype=torch.float32)

add_result = tensor_int + tensor_float
mul_result = tensor_int * tensor_float

print(add_result)
print(mul_result)


tensor([4., 6.])
tensor([3., 8.])


In [56]:
tensor_int = torch.tensor([
    [1,2],
    [1,2]
], dtype=torch.float32)
tensor_float = torch.tensor([
    [3,4],
    [3,4]
], dtype=torch.float32)

matmul_result = tensor_int @ tensor_float
print(matmul_result)

tensor([[ 9., 12.],
        [ 9., 12.]])


In [59]:
tensor = torch.tensor([1,2,3,3,4,5,2])

tensor[-1]

tensor(2)

In [60]:
tensor[::2]

tensor([1, 3, 4, 2])

In [66]:
tensor_2d = torch.tensor([
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8, 10]

])

In [67]:
tensor_2d[0,:3]

tensor([1, 3, 5])

In [68]:
tensor_2d[0, 3:]

tensor([7, 9])

In [69]:
tensor_2d[:, 1:4]

tensor([[3, 5, 7],
        [4, 6, 8]])

In [72]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor(
    [1, -1, 2]
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

torch.matmul(a, b)

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


tensor([ 5, 11])

In [74]:
b_exp = torch.tensor([
    [1, -1, 2],
    [1, -1, 2]
])

a+b_exp

tensor([[2, 1, 5],
        [5, 4, 8]])

In [73]:
a + b

# [1,2,3]. [1,-1,2]
# [4,5,6]. [1,-1,2]

tensor([[2, 1, 5],
        [5, 4, 8]])

In [75]:
a = torch.tensor([
    [-1, 1],
    [1, 1]
])

b = torch.tensor([
    [1, 3]
])

a+ b

tensor([[0, 4],
        [2, 4]])

In [76]:
a + 1

tensor([[0, 2],
        [2, 2]])

In [77]:
a * 2

tensor([[-2,  2],
        [ 2,  2]])

In [78]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor(
    [1, -1, 2]
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

torch.matmul(a, b)

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


tensor([ 5, 11])

### 실습 설명
세 개의 텐서 tensor0, tensor1, tensor2가 주어져 있습니다. 다음 단계를 따라 코드를 작성해 주세요.

tensor0과 tensor1을 더합니다.

1번 결과와 tensor2를 행렬곱합니다.

2번 결과에서 첫 번째 열에는 2를 더하고, 두 번째 열에서는 2를 뺍니다.

3번 결과를 NumPy array로 변환합니다. 이때 변수 이름은 final_np_array로 설정합니다.

### 실습 결과
코드 마지막 부분에서 print() 함수로 출력한 결과가 아래처럼 나와야 합니다.

[[ 6 -6]

 [ 0  0]]

In [80]:
import numpy as np
import torch

tensor0 = torch.tensor(
    [
        [1, 1],
        [-1, -1]
    ]
)
tensor1 = torch.tensor(
    [
        [1, 1],
        [0, 0]
    ]
)
tensor2 = torch.tensor(
    [
        [1, -1],
        [1, -1]
    ]
)

s1 = tensor0 + tensor1
s2 = s1 @ tensor2 # torch.matmul(s1, tensor2)
s2[:, 0] += 2
s2[:, 1] -= 2

final_np_array = s2.numpy()

print(final_np_array)

[[ 6 -6]
 [ 0  0]]


# reshape

In [81]:
x = torch.randn(3, 4)
print(x)

tensor([[-0.1216,  1.3722,  1.3963,  0.7560],
        [ 0.3491,  0.9812,  0.5967,  1.3585],
        [-1.4240, -1.2216, -0.2927,  0.1469]])


In [82]:
resh0 = x.reshape(2, 6)
print(resh0)

tensor([[-0.1216,  1.3722,  1.3963,  0.7560,  0.3491,  0.9812],
        [ 0.5967,  1.3585, -1.4240, -1.2216, -0.2927,  0.1469]])


In [83]:
res0_1 = x.reshape(2, 5)
print(res0_1)

RuntimeError: shape '[2, 5]' is invalid for input of size 12

In [85]:
res1 = x.reshape(-1,2,3)
print(res1)

tensor([[[-0.1216,  1.3722,  1.3963],
         [ 0.7560,  0.3491,  0.9812]],

        [[ 0.5967,  1.3585, -1.4240],
         [-1.2216, -0.2927,  0.1469]]])


In [86]:
x.reshape(-1)

tensor([-0.1216,  1.3722,  1.3963,  0.7560,  0.3491,  0.9812,  0.5967,  1.3585,
        -1.4240, -1.2216, -0.2927,  0.1469])

In [88]:
x = torch.randn(2,3,4)
permuted = x.permute(2, 0, 1)
print(permuted.size)

print(x)
print(permuted)

<built-in method size of Tensor object at 0x7b69aac70650>
tensor([[[ 0.5380, -0.4814, -0.6411, -0.1707],
         [-0.9638, -2.6503,  0.5108, -1.3684],
         [ 0.8152,  0.4590,  1.0500, -0.0040]],

        [[-1.3780, -0.7695,  0.1246, -1.6923],
         [-0.8618,  1.1825,  0.6777, -0.3155],
         [ 2.1317, -0.4948, -1.2971,  0.2381]]])
tensor([[[ 0.5380, -0.9638,  0.8152],
         [-1.3780, -0.8618,  2.1317]],

        [[-0.4814, -2.6503,  0.4590],
         [-0.7695,  1.1825, -0.4948]],

        [[-0.6411,  0.5108,  1.0500],
         [ 0.1246,  0.6777, -1.2971]],

        [[-0.1707, -1.3684, -0.0040],
         [-1.6923, -0.3155,  0.2381]]])


In [89]:
x1 = torch.randn(2, 3)
x2 = x1.t()

print(x1)
print(x2)

tensor([[-1.4837, -1.5884, -0.4665],
        [-1.3057,  0.1202,  0.8787]])
tensor([[-1.4837, -1.3057],
        [-1.5884,  0.1202],
        [-0.4665,  0.8787]])


In [91]:
x = torch.randn(1,4,3)
print(x)
result0 = x.squeeze()
print(result0.size())

tensor([[[ 0.2258,  1.3641, -0.4470],
         [ 1.9920, -1.3121,  1.2288],
         [ 0.4227, -0.1552,  0.2360],
         [ 0.8119,  2.6046,  0.2367]]])
torch.Size([4, 3])


In [93]:
x = torch.randn(1,28,1,28)
result1 = x.squeeze(0)
print(result1.size())

torch.Size([28, 1, 28])


In [94]:
x = torch.randn(28,28,1)
result2 = x.unsqueeze(0)
print(result2.size())

torch.Size([1, 28, 28, 1])


In [95]:
x = torch.randn(3, 4)
res = x.view(2, 6)
print(x)
print(res)

tensor([[-0.9891, -0.1518, -0.4883, -0.5304],
        [-2.0218, -0.5665, -0.1579,  0.7073],
        [ 0.6668, -1.2974,  0.7220,  0.1169]])
tensor([[-0.9891, -0.1518, -0.4883, -0.5304, -2.0218, -0.5665],
        [-0.1579,  0.7073,  0.6668, -1.2974,  0.7220,  0.1169]])


In [96]:
res2 = x.view(-1,2,3)
print(res2)

tensor([[[-0.9891, -0.1518, -0.4883],
         [-0.5304, -2.0218, -0.5665]],

        [[-0.1579,  0.7073,  0.6668],
         [-1.2974,  0.7220,  0.1169]]])


In [97]:
res3 = x.view(-1)
print(res3)

tensor([-0.9891, -0.1518, -0.4883, -0.5304, -2.0218, -0.5665, -0.1579,  0.7073,
         0.6668, -1.2974,  0.7220,  0.1169])


In [99]:
x = torch.ones(2, 3)
x_view = x.view(-1)
x[0,0] = 2
print(x_view)

tensor([2., 1., 1., 1., 1., 1.])


In [100]:
x.is_contiguous()

True

In [102]:
x = torch.ones(3,16,28)
x_permued = x.permute(2,1,0)
x_sliced = x[:,:,:10]


print(x_permued.is_contiguous())
print(x_sliced.is_contiguous())

False
False


In [105]:
x_permued.view(16,3,28)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [106]:
x = torch.rand(2,3,4)
permuted = x.permute(2, 0, 1) #
print(permuted.size())

torch.Size([4, 2, 3])


In [107]:
x = torch.zeros(2,3)
y = torch.ones(2,3)

In [108]:
cat0 = torch.cat([x,y], dim=0)
cat1 = torch.cat([x,y], dim=1)

In [109]:
print(cat0)
print(cat1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])


In [113]:
print('x\n', x)
print('y\n', y)

st0 = torch.stack([x,y], dim=0)
cat0 = torch.cat([x,y], dim=0)

print('stack\n',st0)
print('cat\n',cat0)

x
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
y
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
stack
 tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
cat
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [111]:
print(st0.size())
print(cat0.size())

torch.Size([2, 2, 3])
torch.Size([4, 3])
